### ISSUE TITLE
Hacktoberfest: Collection of new Algorithms needed.

### ISSUE THREAD

**Issue by starkblaze01** [starkblaze01/Algorithms#1]
#### Still confused about what to contribute?
Let's make your task simpler.
This repository contains many algorithms. Found your favorite problem? Then star it 😄 . Can't see your favorite one? Then send a PR an add any algorithms of your choice(e.g. Sorting algorithms, Dynamic Programming, etc.) in your favorite programming language.

P.S.: Please make sure the file name itself is self-explanatory about the Algorithms or make a folder along containing your script and a README explaining the necessary details.

**Comment by ialixandroae** [comment]
Hi ! I can add some.

**Comment by starkblaze01** [comment]
Yeah sure!
Happy Coding!!

**Comment by sriramnjr7** [comment]
Hello!Can I Take This?

**Comment by starkblaze01** [comment]
> Hello!Can I Take This?

Please go ahead 😄

**Comment by starkblaze01** [comment]
Thanks a lot, everyone making hacktober successful this year!!!
Will see you all next year again with some new collection. Till then keep coding!!
